<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Advertise\Module'                        => __DIR__ . '/Module.php',
    'Advertise\Controller\AdvertiseController' => __DIR__ . '/src/Advertise/Controller/AdvertiseController.php',
    'AdvertiseTest\Framework\TestCase'        => __DIR__ . '/tests/Advertise/Framework/TestCase.php',
    'AdvertiseTest\SampleTest'                => __DIR__ . '/tests/Advertise/SampleTest.php',
);
