<table cellspacing="0" cellpadding="0" border="0">
    <tbody>
        <tr>
            <td style="padding:15px 15px 0 15px;background:#fff;border-radius:4px 4px 0 0">
                <div>
                    <img src="http://www.heqs.com.au/images/heqs_logo.png" alt="HEQS Group" height="85" width="290">
                </div>
            </td>
        </tr>
        <tr>
            <td style="padding:15px; background:#fff; border-radius:0 0 4px 4px;font-size:12px">
                
                <?php echo $this->emailAddr?> has been blocked by Gumtree. <br>
                <?php echo $this->message;?><br/>
                <div style="border-top:3px solid #eee;color:#999;font-size:11px;line-height:1.2">
                    <br>Powered by <a href="http://www.heqs.com.au" target="_blank" style="color: #005399;text-decoration: none;">HEQS Group</a>. All rights reserved.<br>
                </div>
            </td>
        </tr>
    </tbody>
</table>
